"""add cloudflare_credentials table

Revision ID: 3603b4e517f3
Revises: c029f15faa8d
Create Date: 2026-05-03 17:04:51.408845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3603b4e517f3'
down_revision: Union[str, None] = 'c029f15faa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudflare_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('api_token_encrypted', sa.Text(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cloudflare_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cloudflare_credentials_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloudflare_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cloudflare_credentials_org_id'))

    op.drop_table('cloudflare_credentials')
    # ### end Alembic commands ###
