"""cloudflare-managed dns columns on custom_domains

Revision ID: 4183fe5d8e83
Revises: 3603b4e517f3
Create Date: 2026-05-03 17:20:01.289113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4183fe5d8e83'
down_revision: Union[str, None] = '3603b4e517f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudflare_credential_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('cloudflare_zone_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cloudflare_record_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cloudflare_target_ip', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cloudflare_synced_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_custom_domains_cloudflare_credential_id'), ['cloudflare_credential_id'], unique=False)
        batch_op.create_foreign_key('fk_custom_domains_cf_credential', 'cloudflare_credentials', ['cloudflare_credential_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_domains', schema=None) as batch_op:
        batch_op.drop_constraint('fk_custom_domains_cf_credential', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_custom_domains_cloudflare_credential_id'))
        batch_op.drop_column('cloudflare_synced_at')
        batch_op.drop_column('cloudflare_target_ip')
        batch_op.drop_column('cloudflare_record_id')
        batch_op.drop_column('cloudflare_zone_id')
        batch_op.drop_column('cloudflare_credential_id')

    # ### end Alembic commands ###
