"""add password_entries vault

Revision ID: 52e21baa63f8
Revises: 7f496ea8f772
Create Date: 2026-07-08 19:45:22.685490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e21baa63f8'
down_revision: Union[str, None] = '7f496ea8f772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_entries_user_id'))

    op.drop_table('password_entries')
    # ### end Alembic commands ###
