"""add photo backups + devices

Revision ID: 7f496ea8f772
Revises: a1b2c3d4e5f6
Create Date: 2026-07-08 19:24:05.432510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f496ea8f772'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_backup_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_backup_devices_token_hash'), 'photo_backup_devices', ['token_hash'], unique=True)
    op.create_index(op.f('ix_photo_backup_devices_user_id'), 'photo_backup_devices', ['user_id'], unique=False)
    op.create_table('photo_backups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('READY', 'FAILED', name='photobackupstatus'), nullable=False),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['photo_backup_devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sha256', name='uq_photo_backups_user_sha')
    )
    op.create_index(op.f('ix_photo_backups_device_id'), 'photo_backups', ['device_id'], unique=False)
    op.create_index(op.f('ix_photo_backups_sha256'), 'photo_backups', ['sha256'], unique=False)
    op.create_index(op.f('ix_photo_backups_user_id'), 'photo_backups', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_backups_user_id'), table_name='photo_backups')
    op.drop_index(op.f('ix_photo_backups_sha256'), table_name='photo_backups')
    op.drop_index(op.f('ix_photo_backups_device_id'), table_name='photo_backups')
    op.drop_table('photo_backups')
    op.drop_index(op.f('ix_photo_backup_devices_user_id'), table_name='photo_backup_devices')
    op.drop_index(op.f('ix_photo_backup_devices_token_hash'), table_name='photo_backup_devices')
    op.drop_table('photo_backup_devices')
    # ### end Alembic commands ###
