"""add cloudflare_tunnel_id to custom_domains

Revision ID: 86eb92ce0a55
Revises: de07c87db2a6
Create Date: 2026-06-24 01:03:18.799646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86eb92ce0a55'
down_revision: Union[str, None] = 'de07c87db2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudflare_tunnel_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_domains', schema=None) as batch_op:
        batch_op.drop_column('cloudflare_tunnel_id')

    # ### end Alembic commands ###
