"""add oidc_subject to users

Revision ID: c4d8f1a5e2b9
Revises: ba7a02a0d95d
Create Date: 2026-09-28

Hand-written (not autogenerated) and scoped to the single column this
migration is named for — ``users.oidc_subject``, the stable identity for
generic-OIDC logins ("<issuer>|<sub>"). Autogenerate on a dev DB that's
behind on other models sweeps in unrelated tables; keeping this by-hand
avoids that and keeps the history reviewable.

SQLite can't add a UNIQUE column inline, so the unique index is created
separately (works on both SQLite and Postgres). Existing rows get NULL,
which a partial/standard unique index permits for multiple NULLs on both
backends.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c4d8f1a5e2b9"
down_revision: Union[str, None] = "ba7a02a0d95d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("oidc_subject", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_users_oidc_subject"), ["oidc_subject"], unique=True
        )


def downgrade() -> None:
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_oidc_subject"))
        batch_op.drop_column("oidc_subject")
