"""add triggered_by_user_id to deployments

Revision ID: de07c87db2a6
Revises: a7c92e4f5d18
Create Date: 2026-06-23 09:06:15.031072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de07c87db2a6'
down_revision: Union[str, None] = 'a7c92e4f5d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_deployments_triggered_by_user_id'), ['triggered_by_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_triggered_by_user_id'))
        batch_op.drop_column('triggered_by_user_id')

    # ### end Alembic commands ###
