"""add backup_destinations and backup_copies

Revision ID: df983087a51a
Revises: 52e21baa63f8
Create Date: 2026-07-08 02:00:37.230265

Note: originally authored against down_revision 86eb92ce0a55, then re-pointed
to 52e21baa63f8 (the Passwords-vault migration) when this branch was rebased
onto origin/main — origin had added migrations off the same parent, which
would have produced two Alembic heads. Re-pointing keeps a single linear chain.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df983087a51a'
down_revision: Union[str, None] = '52e21baa63f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_destinations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('PEER', 'FOLDER', name='backupdestinationkind'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('remote_subdir', sa.String(), nullable=True),
    sa.Column('folder_path', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['org_nodes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_destinations_org_id'), ['org_id'], unique=False)

    op.create_table('backup_copies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COPIED', 'FAILED', name='backupcopystatus'), nullable=False),
    sa.Column('dest_path', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['managed_database_backups.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['backup_destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backup_id', 'destination_id', name='uq_backup_copy_backup_dest')
    )
    with op.batch_alter_table('backup_copies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_copies_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_copies_destination_id'), ['destination_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_copies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_copies_destination_id'))
        batch_op.drop_index(batch_op.f('ix_backup_copies_backup_id'))

    op.drop_table('backup_copies')
    with op.batch_alter_table('backup_destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_destinations_org_id'))

    op.drop_table('backup_destinations')
    # ### end Alembic commands ###
