"""Canonical legal documents shown in-app and accepted at first login.

These live in a Python module (not loose .md files) so packaged builds —
wheels, DMGs, AppImages — always ship them; the PyPI wheel has already
bitten us once for relying on repo-relative data files. The repo-root
``legal/*.md`` copies exist for GitHub readability and MUST be kept in
sync with these constants (see legal/README.md).

``TERMS_VERSION`` is the acceptance anchor: bumping it forces every user
through the click-through gate again on their next login. Bump it for
any change a reasonable person would want re-notified about (new data
flows, new autonomous behaviour, liability changes) — not for typo fixes.

NOTE FOR MAINTAINERS: this text was drafted to protect the project but
has not been reviewed by an attorney. Before any commercial launch, have
counsel review and pin the governing-law clause to a real jurisdiction.
"""
from __future__ import annotations

TERMS_VERSION = "1.0"
TERMS_EFFECTIVE_DATE = "2026-06-12"

TERMS_OF_USE = """\
# WatchTower Terms of Use

**Version {version} — effective {date}**

These Terms of Use ("Terms") govern your use of the WatchTower software
("the Software"), published by the WatchTower authors and copyright
holder ("the Authors"). By signing in to a WatchTower installation, or
by clicking "I agree", you accept these Terms. If you do not agree, do
not use the Software.

The Software's source code is licensed separately under the Apache
License 2.0 and the Elastic License 2.0 (see the LICENSE files). These
Terms govern your *use* of a running installation; they do not limit
rights granted to you by those licenses.

## 1. Self-hosted software — you are the operator

WatchTower is self-hosted. It runs on infrastructure **you** own or
control, deploys workloads **you** choose, and connects to services
**you** configure. The Authors do not host, monitor, or have access to
your installation, your data, or your infrastructure.

You are solely responsible for:

- the machines, networks, and accounts the Software runs on or connects to;
- the safekeeping of credentials you give it (API tokens, GitHub
  credentials, SSH keys, cloud provider keys, database passwords);
- backups of your data, including the WatchTower database and encryption keys;
- everything the Software deploys, runs, restarts, updates, or deletes
  at your direction or under configurations you enabled;
- compliance with all laws and regulations that apply to you and your
  use, including data-protection laws (e.g. GDPR, CCPA) where you act
  as a controller or processor of other people's data, export-control
  and sanctions laws, and the terms of every third-party service you
  connect.

## 2. Automated and AI-assisted features

The Software includes automation that, **when you enable it**, acts on
your infrastructure without a human in the loop: container auto-update,
health-probe restart and rollback, and autonomous self-heal (automatic
fixes and redeploys of failed deployments). These features are disabled
or conservative by default, are clearly labelled in the interface, and
provide human-approval alternatives.

The Software can also connect to a large-language-model endpoint **that
you configure**. LLM output is generated by your chosen model, may be
inaccurate, incomplete, or unsafe, and is provided for your evaluation
only. When AI features are enabled, deployment logs and related context
are sent to the endpoint you configured — choose that endpoint with
care.

**By enabling any automated or AI-assisted feature you accept full
responsibility for its actions and output.** The Authors are not liable
for any action taken by automation you enabled, including lost data,
downtime, or unintended changes to your systems.

## 3. Acceptable use

Your use is subject to the Acceptable Use Policy, which is part of
these Terms.

## 4. Third-party services

The Software interoperates with third-party services (GitHub,
Cloudflare, cloud providers, container registries, LLM providers, and
others) under **your** accounts and **their** terms. The Authors are
not party to those relationships and are not responsible for those
services, their availability, or charges you incur on them.

## 5. No warranty

THE SOFTWARE IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTY
OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE,
AND NON-INFRINGEMENT. THE AUTHORS DO NOT WARRANT THAT THE SOFTWARE WILL
BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT IT WILL PRESERVE YOUR
DATA OR THE AVAILABILITY OF YOUR DEPLOYED WORKLOADS.

## 6. Limitation of liability

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL THE
AUTHORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE,
DATA, OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR USE OF THE
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE
AUTHORS' TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THE
SOFTWARE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID THE
AUTHORS FOR THE SOFTWARE IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR
(B) ONE HUNDRED US DOLLARS (USD 100).

Some jurisdictions do not allow certain limitations; in those
jurisdictions these limitations apply to the fullest extent permitted.

## 7. Indemnification

You will defend, indemnify, and hold harmless the Authors from and
against any claims, damages, liabilities, costs, and expenses
(including reasonable legal fees) arising out of (a) your use of the
Software, (b) workloads, content, or data you deploy or process with
it, (c) your violation of these Terms or of applicable law, or (d)
your violation of any third party's rights.

## 8. Privacy

The Privacy Policy describes what the Software stores and where data
flows. It is part of these Terms. In short: your data stays on your
installation; the Authors receive nothing unless you explicitly send it
(for example, a bug report).

## 9. Multi-user installations

If you operate a WatchTower installation that other people sign in to,
you are responsible for those users, for presenting these Terms to
them (the Software does this at first login), and for your own legal
obligations toward them.

## 10. Changes

The Authors may update these Terms. The Software will ask you to review
and re-accept after a material change. Continued use after acceptance
constitutes agreement.

## 11. General

These Terms are the entire agreement between you and the Authors
regarding use of a running installation, and are severable — if a
provision is unenforceable, the rest remains in effect. Failure to
enforce a provision is not a waiver. You may not use the Software if
you are barred from doing so under applicable law.

**Contact:** opensource@sinhaankur.dev
""".format(version=TERMS_VERSION, date=TERMS_EFFECTIVE_DATE)


ACCEPTABLE_USE_POLICY = """\
# WatchTower Acceptable Use Policy

**Version {version} — effective {date}**

This policy is part of the WatchTower Terms of Use. It exists to keep
the Software, its users, and third parties out of harm's way. You agree
NOT to use the Software to:

1. **Break the law.** No use that violates any applicable law or
   regulation, including computer-misuse, privacy, intellectual-
   property, export-control, and sanctions laws.

2. **Attack systems you don't control.** The deployment, SSH, and
   provisioning tooling may only target machines and accounts you own
   or are explicitly authorized to manage. No unauthorized access, no
   scanning or exploiting third-party systems, no denial-of-service.

3. **Host or distribute harmful content.** No deploying malware,
   phishing infrastructure, command-and-control services, or content
   that is illegal in the jurisdictions where you operate.

4. **Infringe rights.** No deploying or distributing content that
   infringes copyright, trademark, trade secrets, or privacy or
   publicity rights of others.

5. **Abuse third-party services.** Respect the terms and rate limits of
   every service you connect (GitHub, registries, DNS and cloud
   providers, LLM providers). Charges and penalties on those services
   are yours.

6. **Misrepresent the Software.** Don't remove or falsify license
   notices, and don't present a modified installation as an official
   release of the Authors.

7. **Circumvent licensing.** Features under the Elastic License 2.0
   (`pro/`) may not be offered to third parties as a managed service or
   have their license-key functionality circumvented, per ELv2.

Operators of multi-user installations are responsible for enforcing
this policy with their users. Violations may expose you to liability;
the Authors accept none for prohibited use.

**Contact:** opensource@sinhaankur.dev
""".format(version=TERMS_VERSION, date=TERMS_EFFECTIVE_DATE)


PRIVACY_POLICY = """\
# WatchTower Privacy Policy

**Version {version} — effective {date}**

WatchTower is self-hosted: your data lives on **your** installation.
The Authors operate no servers for the Software, collect no telemetry,
and cannot see your data. This policy describes what the Software
stores locally and where data flows so you can operate it responsibly.

## What the Software stores (locally, on your machine)

- **Account data** from GitHub sign-in: your GitHub ID, username,
  email address, and avatar URL.
- **Operational data**: projects, deployments, build logs, node
  definitions, managed-database metadata, healing/self-heal decisions.
- **Secrets you provide** — GitHub tokens, SSH keys, environment-
  variable values, database passwords, API keys — stored encrypted
  (Fernet) with a key kept at `~/.watchtower/secret.key` (0600).
- **Audit log**: who did what, when, from which IP address — including
  acceptance of these legal documents. Append-only, for accountability
  on multi-user installations.

Default location: `~/.watchtower/` (or `DATABASE_URL` if configured).
Deleting that directory deletes the data. Backups you export contain
the encryption key and all secrets — guard them accordingly.

## Where data flows (only to services you configure)

- **GitHub** — for sign-in (OAuth / Device Flow), repository access,
  webhooks, and checking for new WatchTower releases.
- **Your deploy targets** — code, artifacts, and commands travel to
  your nodes over SSH.
- **Your LLM endpoint** — when you enable AI features, deployment logs
  and related context are sent to the OpenAI-compatible endpoint you
  configured (e.g. LM Studio or Ollama on localhost, or a cloud
  provider). Nothing is sent until you configure one.
- **DNS / cloud providers** — only when you connect them (Cloudflare,
  cloud credentials).
- **Bug reports** — only when you explicitly send one; review the
  attached diagnostics before sending.

There is **no** analytics, tracking, or "phone home" beyond the
release-update check against GitHub, which can be disabled in Settings.

## Your responsibilities as operator

If other people sign in to your installation, or workloads you deploy
process other people's personal data, **you** are the data controller.
Applicable data-protection law (GDPR, CCPA, and similar) is your
obligation, including informing your users and honoring their rights.
The audit log and encrypted-secret storage are tools to help you, not
a substitute for your own compliance.

## Contact

Questions about this policy: opensource@sinhaankur.dev
""".format(version=TERMS_VERSION, date=TERMS_EFFECTIVE_DATE)


# Ordered as presented in the acceptance gate.
DOCUMENTS = [
    {"id": "terms", "title": "Terms of Use", "content": TERMS_OF_USE},
    {"id": "acceptable-use", "title": "Acceptable Use Policy", "content": ACCEPTABLE_USE_POLICY},
    {"id": "privacy", "title": "Privacy Policy", "content": PRIVACY_POLICY},
]
