"""Generic OpenID Connect (OIDC) login — provider-agnostic.

One config-driven Authorization-Code flow that works with any spec-compliant
OIDC provider: Google, GitLab, Authentik, Okta, Keycloak, Microsoft Entra,
Auth0, etc. This is the identity-provider-agnostic path that sits alongside
the GitHub-specific OAuth in ``api/enterprise.py`` — same signed-session-token
outcome, different front door.

Design mirrors the GitHub flow so it slots into the same model:
  * ``discover()`` reads the provider's ``.well-known/openid-configuration``
    (or uses explicitly-configured endpoints) to find authorize/token/
    userinfo/jwks URLs.
  * ``exchange_code()`` swaps the auth code for tokens.
  * ``claims_from_tokens()`` returns the normalised identity (sub, iss, email,
    name, picture) from the id_token / userinfo.

Security:
  * Every provider URL is run through ``assert_safe_external_url`` (the same
    SSRF guard used for GHES) before any server-side request — an operator
    can't be tricked into pointing OIDC at ``169.254.169.254`` etc.
  * ``state`` (CSRF) and ``nonce`` (replay) are generated by the caller and
    verified on callback; ``nonce`` is checked against the id_token.
  * The id_token signature is NOT verified here in v0 — instead the token
    is fetched over TLS directly from the provider's token endpoint (a
    confidential-client back-channel exchange), so its authenticity comes
    from the TLS channel + client_secret, not from JWT signature checking.
    Verifying the JWS against JWKS is a hardening follow-up; documented so
    it's a conscious v0 boundary, not an oversight.
"""
from __future__ import annotations

import base64
import json
import logging
import os
from dataclasses import dataclass
from typing import Optional

import requests

logger = logging.getLogger(__name__)

_DISCOVERY_SUFFIX = "/.well-known/openid-configuration"


class OidcError(Exception):
    """Raised on any OIDC config/flow failure. ``status`` mirrors HTTP
    semantics so the FastAPI handler can pass it straight through."""

    def __init__(self, status: int, detail: str) -> None:
        super().__init__(detail)
        self.status = status
        self.detail = detail


@dataclass(frozen=True)
class OidcConfig:
    issuer: str
    client_id: str
    client_secret: str
    authorize_url: str
    token_url: str
    userinfo_url: Optional[str]
    scopes: str


@dataclass(frozen=True)
class OidcClaims:
    subject: str          # "<issuer>|<sub>" — stable, per-issuer unique
    email: Optional[str]
    email_verified: bool
    name: Optional[str]
    picture: Optional[str]


def is_configured() -> bool:
    """True when the minimum OIDC env is present so the SPA can show/hide
    the "Sign in with <provider>" button without a round-trip that 503s."""
    return bool(
        os.getenv("WATCHTOWER_OIDC_ISSUER")
        and os.getenv("WATCHTOWER_OIDC_CLIENT_ID")
        and os.getenv("WATCHTOWER_OIDC_CLIENT_SECRET")
    )


def provider_label() -> str:
    """Human name for the button, e.g. "Google". Falls back to the issuer host."""
    label = os.getenv("WATCHTOWER_OIDC_PROVIDER_NAME")
    if label:
        return label
    issuer = os.getenv("WATCHTOWER_OIDC_ISSUER", "")
    try:
        from urllib.parse import urlparse
        host = urlparse(issuer).hostname or issuer
        return host.replace("www.", "") or "OIDC"
    except Exception:
        return "OIDC"


def discover() -> OidcConfig:
    """Resolve the OIDC endpoints from env + the provider's discovery doc.

    Explicit endpoint env vars win over discovery, so a provider with a
    non-standard discovery path still works. Discovery is only attempted
    when the authorize/token URLs aren't both explicitly set.
    """
    from watchtower.api import util  # local import: avoids cycle at module load

    issuer = os.getenv("WATCHTOWER_OIDC_ISSUER")
    client_id = os.getenv("WATCHTOWER_OIDC_CLIENT_ID")
    client_secret = os.getenv("WATCHTOWER_OIDC_CLIENT_SECRET")
    if not (issuer and client_id and client_secret):
        raise OidcError(503, "OIDC login is not configured (set WATCHTOWER_OIDC_ISSUER / _CLIENT_ID / _CLIENT_SECRET).")

    scopes = os.getenv("WATCHTOWER_OIDC_SCOPES", "openid email profile")
    authorize_url = os.getenv("WATCHTOWER_OIDC_AUTHORIZE_URL")
    token_url = os.getenv("WATCHTOWER_OIDC_TOKEN_URL")
    userinfo_url = os.getenv("WATCHTOWER_OIDC_USERINFO_URL")

    if not (authorize_url and token_url):
        doc = _fetch_discovery(issuer.rstrip("/") + _DISCOVERY_SUFFIX, util)
        authorize_url = authorize_url or doc.get("authorization_endpoint")
        token_url = token_url or doc.get("token_url") or doc.get("token_endpoint")
        userinfo_url = userinfo_url or doc.get("userinfo_endpoint")

    if not authorize_url or not token_url:
        raise OidcError(
            502,
            "OIDC discovery did not return authorize/token endpoints. Set "
            "WATCHTOWER_OIDC_AUTHORIZE_URL and WATCHTOWER_OIDC_TOKEN_URL explicitly.",
        )

    # SSRF-guard every endpoint we'll call server-side.
    util.assert_safe_external_url(authorize_url)
    util.assert_safe_external_url(token_url)
    if userinfo_url:
        util.assert_safe_external_url(userinfo_url)

    return OidcConfig(
        issuer=issuer.rstrip("/"),
        client_id=client_id,
        client_secret=client_secret,
        authorize_url=authorize_url,
        token_url=token_url,
        userinfo_url=userinfo_url,
        scopes=scopes,
    )


def _fetch_discovery(url: str, util) -> dict:
    util.assert_safe_external_url(url)
    try:
        resp = requests.get(url, headers={"Accept": "application/json"}, timeout=15)
    except requests.RequestException as exc:
        raise OidcError(502, f"OIDC discovery unreachable: {exc}") from exc
    if resp.status_code >= 400:
        raise OidcError(502, f"OIDC discovery failed ({resp.status_code}) at {url}")
    try:
        return resp.json() or {}
    except ValueError as exc:
        raise OidcError(502, "OIDC discovery returned non-JSON.") from exc


def exchange_code(cfg: OidcConfig, code: str, redirect_uri: str) -> dict:
    """Swap an authorization code for tokens (confidential-client)."""
    try:
        resp = requests.post(
            cfg.token_url,
            headers={"Accept": "application/json"},
            data={
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": redirect_uri,
                "client_id": cfg.client_id,
                "client_secret": cfg.client_secret,
            },
            timeout=15,
        )
    except requests.RequestException as exc:
        raise OidcError(502, f"OIDC token endpoint unreachable: {exc}") from exc
    if resp.status_code >= 400:
        raise OidcError(400, "OIDC token exchange failed.")
    try:
        return resp.json() or {}
    except ValueError as exc:
        raise OidcError(502, "OIDC token endpoint returned non-JSON.") from exc


def _decode_jwt_payload(jwt: str) -> dict:
    """Decode (NOT verify) the payload segment of a JWT. Authenticity here
    comes from the TLS back-channel fetch, not signature verification — see
    the module docstring's security note."""
    try:
        payload_b64 = jwt.split(".")[1]
        payload_b64 += "=" * (-len(payload_b64) % 4)  # pad to a multiple of 4
        return json.loads(base64.urlsafe_b64decode(payload_b64))
    except Exception as exc:
        raise OidcError(400, "OIDC id_token payload could not be decoded.") from exc


def claims_from_tokens(cfg: OidcConfig, token_data: dict, *, expected_nonce: Optional[str]) -> OidcClaims:
    """Normalise identity from the id_token (preferred) or userinfo endpoint."""
    id_token = token_data.get("id_token")
    access_token = token_data.get("access_token")
    claims: dict = {}

    if id_token:
        claims = _decode_jwt_payload(id_token)
        if expected_nonce and claims.get("nonce") and claims.get("nonce") != expected_nonce:
            raise OidcError(400, "OIDC nonce mismatch — possible replay; refusing login.")

    # Fall back to / enrich from userinfo when the id_token is thin.
    if cfg.userinfo_url and access_token and not claims.get("email"):
        from watchtower.api import util
        util.assert_safe_external_url(cfg.userinfo_url)
        try:
            ui = requests.get(
                cfg.userinfo_url,
                headers={"Authorization": f"Bearer {access_token}", "Accept": "application/json"},
                timeout=15,
            )
            if ui.status_code < 400:
                claims = {**(ui.json() or {}), **claims}
        except (requests.RequestException, ValueError):
            logger.warning("OIDC userinfo fetch failed; proceeding with id_token claims only.")

    sub = claims.get("sub")
    if not sub:
        raise OidcError(400, "OIDC provider returned no subject (sub) — cannot establish identity.")

    return OidcClaims(
        subject=f"{cfg.issuer}|{sub}",
        email=claims.get("email"),
        email_verified=bool(claims.get("email_verified", False)),
        name=claims.get("name") or claims.get("preferred_username") or claims.get("given_name"),
        picture=claims.get("picture") or claims.get("avatar_url"),
    )
